AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds.rb'
  TargetRubyVersion: 2.6.3
Documentation:
  Enabled: false

ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Max: 120

Metrics/BlockNesting:
  Max: 5

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 20

Style/ClassAndModuleChildren:
  Enabled: false
